# 设备设置
device: "auto"  # 可选: auto, cuda, cpu

# 基准目录配置（相对于项目根目录 IEDA_WeightedTraining）
base_dir: "."  # 项目根目录

# 数据集设置
# Pure 或 1K 或 27K
dataset_name: "Pure"
data_path: "KuaiRand/Pure/data/"
results_path: "results/"

# 缓存设置
enable_cache: true
cache_dir: "KuaiRand/cache/"

# 实验设置
experiment_method: "weighted" # 可选: weighted, pooling, splitting, snapshot
repetitions: 100
p_treatment: 0.5


# 动态模拟循环参数
total_simulation_steps: 1000
candidate_pool_size: 100
initial_dataset_size: 5000
train_every_n_steps: 20
batch_size: 128


# 模型超参数
prediction_model:
  input_dim: 102
  shared_dims: [32]
  ctr_head_dims: [16, 8]
  playtime_head_dims: [16, 8]
  separate_models: false  # 是否分离CTR和播放时间预测模型
  
# CTR模型单独配置 (当 separate_models=true 时使用)
ctr_model:
  input_dim: 102
  hidden_dims: [64, 32, 16]
  
# 播放时间模型单独配置 (当 separate_models=true 时使用)  
playtime_model:
  input_dim: 102
  hidden_dims: [64, 32, 16]
  
# 损失函数权重调节
loss_weights:
  ctr_weight: 1.0          # CTR损失权重
  playtime_weight: 0.0001  # 播放时间损失权重，大幅减小
  
weighting_model:
  hidden_dims: [16, 8]

# 推荐器参数
recommender:
  treatment_alpha: 0.5
  control_alpha: 0.05

# 日志与保存
log_path: "results/logs/"
checkpoint_path: "results/checkpoints/"
plot_path: "results/plots/"

# 数据加载优化
load_features: ["user", "video_basic", "video_statistic"]  # 可选的特征类型
chunk_size: 10000  # 分块加载大小
use_multiprocessing: false  # 是否使用多进程加载

# 其他参数可根据需要补充
