# base_dir: "/home/zhixuanhu/IEDA_WeightedTraining/RealdataEXP"
base_dir: "/home/export/base/sc100352/sc100352/online1/IEDA_WeightedTraining/RealdataEXP"
mode: 'global_optimized'  # 使用优化模式

# --- Device Configuration ---
# Specifies the hardware backend.
# Options:
#   'auto': (Recommended) Automatically detects best available hardware in order: cuda -> ipex -> xpu -> dml -> cpu
#   'cuda': NVIDIA GPU with full AMP support.
#   'ipex': Intel GPU with full IPEX optimizations and AMP support.
#   'xpu':  Intel GPU with basic device placement only (No IPEX optimizations, no AMP).
#   'dml':  DirectML-compatible GPU (AMD, Intel, etc.) (No AMP).
#   'cpu':  CPU execution.
device: 'auto'

# 数据集配置
dataset:
  name: "KuaiRand-1K"
  path: "data/KuaiRand/1K"  # 1K数据在KuaiRand/1K目录下
  cache_path: "data/KuaiRand/cache"
  # --- 新增: DataLoader优化参数 ---
  num_workers: 64  # 使用32个CPU核心进行并行数据加载
  pin_memory: true # 锁定内存，加速CPU到GPU的数据传输

# dataset:
#   name: "KuaiRand-Pure"
#   path: "data/KuaiRand/Pure"  # 1K数据在KuaiRand/1K目录下
#   cache_path: "data/KuaiRand/cache"
#   # --- 新增: DataLoader优化参数 ---
#   num_workers: 96  # 使用32个CPU核心进行并行数据加载
#   pin_memory: true # 锁定内存，加速CPU到GPU的数据传输

# 启用混合精度训练
use_amp: true

# 特征配置（27K数据集特征）
feature:
  numerical:
    - "video_duration"
    - "server_width"
    - "server_height"
    - "show_cnt"
    - "play_cnt"
    - "play_user_num"
    - "complete_play_cnt"
    - "like_cnt"
    - "comment_cnt"
    - "share_cnt"
    - "collect_cnt"
    - "is_live_streamer"
    - "is_video_author"
    - "follow_user_num"
    - "fans_user_num"
    - "friend_user_num"
    - "register_days"
  categorical:
    - "user_active_degree"
    - "video_type"
    - "tag"

# 标签配置（调整了模型参数以提升效果）
labels:
  - name: "play_time"
    target: "play_time_ms"
    type: "numerical"
    loss_function: "logMAE"
    model: "MLP"
    model_params:
      hidden_layers: [256, 128, 64, 32]  # 增加模型容量
      dropout: 0.3  # 增加dropout防止过拟合
      # dropout: 0.0 # dml会减速
      embedding_dim: 32  # 增加嵌入维度
    learning_rate: 0.001  # 稍微增加学习率
    weight_decay: 0.0005
    alpha_T: 1.0
    alpha_C: 0.5
    
  - name: "click"
    target: "is_click"
    type: "binary"
    loss_function: "BCE"
    model: "MLP"
    model_params:
      hidden_layers: [128, 64, 32, 16]  # 增加模型容量
      dropout: 0.2  # 适度dropout
      # dropout: 0.0
      embedding_dim: 16  # 增加嵌入维度
    learning_rate: 0.001  # 稍微增加学习率
    weight_decay: 0.0005
    alpha_T: 1.0
    alpha_C: 0.8

# 预训练配置（优化）
pretrain:
  enabled: true
  batch_size: 256  # 增加batch size以更好利用GPU
  epochs: 150  
  learning_rate: 0.001
  weight_decay: 0.0005
  early_stopping: 10
  # --- 新增配置 ---
  # 指定要加载的预训练权重文件路径，如果为null则不加载
  load_checkpoint_path: null # example: "results/20250818_0110/checkpoints/pretrain_epoch_1.pt"
  # 预训练数据的验证集划分比例
  val_split_ratio: 0.5
  # 是否在每个epoch后绘制并保存损失曲线图
  plot_loss_curves: true
  # --- 新增：基于迭代次数的验证频率 ---
  validate_every_iters: 500

# 全局仿真配置（优化）
global:
  user_p_val: 0.2
  batch_size: 128  # 增加batch size
  n_candidate: 10
  n_steps: 5  # 减少步数以便快速测试优化效果
  validate_every: 1  # 更频繁的验证
  save_every: 25
  learning_rate: 0.001
  weight_decay: 0.0005

# 日志配置
logging:
  level: "INFO"
  log_dir: "results"

# --- 新增：验证配置 ---
validation:
  primary_metric: "val_play_time_loss"  # 用于保存"最佳整体"模型的主要指标
